# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    volumes:
      - ./src:/src
    environment:
      - LLM_API_KEY=XXXXXXXreplaceXXXXXXXXX  
      - AWS_ACCESS_KEY_ID=replace
      - AWS_SECRET_ACCESS_KEY=replace

    command: >
      sh -c "streamlit run main.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - 8501:8501
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
