# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    volumes:
      - ./src:/src
      - ./S3:/mnt/s3
    environment:
      - LLM_API_KEY=AIzaSyBG5TCCSusvqD7sCnrZfz6TgHoRpJJIxXM
    command: >
      sh -c "streamlit run main.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - 8501:8501
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
